import type { JobPosition } from "./types";

export const data: JobPosition[] = [
  {
    id: "1",
    company: "Software House AI",
    positionName: "Design Frontend Engineer",
    publishedAt: new Date("2025-03-13"),
    location: ["US"],
    skills: ["Frontend Architecture"],
    experience: [5],
    employmentType: "fulltime",
    applicationStatus: "not-applied",
    category: "frontend",
  },
  {
    id: "2",
    company: "Software House AI",
    positionName: "Frontend Engineer",
    publishedAt: new Date("2025-03-14"),
    location: ["US", "CA"],
    skills: ["React", "Next.js"],
    experience: [5, 15],
    employmentType: "fulltime",
    applicationStatus: "not-applied",
    category: "frontend",
  },
  {
    id: "7",
    company: "Software House AI",
    positionName: "Frontend Engineer",
    publishedAt: new Date("2025-03-14"),
    location: ["US", "CA"],
    skills: ["React", "Javascript", "Next.js"],
    experience: [undefined, 15],
    length: 1,
    employmentType: "contract",
    applicationStatus: "not-applied",
    category: "frontend",
  },
  {
    id: "3",
    company: "Image Processing LLC",
    positionName: "Frontend Developer",
    publishedAt: new Date("2025-03-15"),
    location: [
      "AT",
      "BE",
      "BG",
      "HR",
      "CY",
      "CZ",
      "DK",
      "EE",
      "FI",
      "FR",
      "DE",
      "GR",
      "HU",
      "IE",
      "IT",
      // "LV",
      // "LT",
      // "LU",
      // "MT",
      // "NL",
      // "PL",
      // "PT",
      // "RO",
      // "SK",
      // "SI",
      // "ES",
      // "SE",
      // "GB",
      // "AR",
      // "BO",
      // "BR",
      // "CL",
      // "CO",
      // "CR",
      // "CU",
      // "DO",
      // "EC",
      // "SV",
      // "GT",
      // "HT",
      // "HN",
      // "MX",
      // "NI",
      // "PA",
      // "PY",
      // "PE",
      // "PR",
      // "UY",
      // "VE",
    ],
    skills: ["React"],
    experience: [8, 15],
    length: 2,
    employmentType: "fulltime",
    applicationStatus: "not-applied",
    category: "frontend",
  },
  {
    id: "4",
    company: "Wizard Labs",
    positionName: "Data Engineer (Web Scraping)",
    publishedAt: new Date("2025-03-03"),
    location: ["ALL"],
    skills: ["Python", "Data Visualization"],
    experience: [5, 8],
    employmentType: "fulltime",
    applicationStatus: "not-applied",
    category: "data analyst",
  },
  {
    id: "5",
    company: "Heart Health",
    positionName: "Senior Full Stack Engineer",
    publishedAt: new Date("2024-10-29"),
    location: ["US"],
    skills: ["React", "UI Development"],
    employmentType: "fulltime",
    applicationStatus: "not-applied",
    category: "fullstack",
  },
  {
    id: "6",
    company: "Jeans",
    positionName: "Software Engineer",
    publishedAt: new Date("2024-11-01"),
    location: [
      "AR",
      "BO",
      "BR",
      "CL",
      "CO",
      "CR",
      "CU",
      "DO",
      "EC",
      "SV",
      "GT",
      "HT",
      "HN",
      "MX",
      "NI",
      "PA",
      "PY",
      "PE",
      "PR",
      "UY",
      "VE",
    ],
    skills: ["React", "Elixir"],
    experience: [3, 5],
    length: 6,
    employmentType: "contract",
    applicationStatus: "not-applied",
    category: "fullstack",
  },
];

export const localeDateOptions: Intl.DateTimeFormatOptions = {
  day: "numeric",
  month: "short",
  year: "numeric",
};
